export const GET_ALL_NEWS_START = 'GET_ALL_NEWS_START';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_FAIL = 'GET_ALL_NEWS_FAIL';

export const GET_BUSINESS_NEWS_START = 'GET_BUSINESS_NEWS_START';
export const GET_BUSINESS_NEWS_SUCCESS = 'GET_BUSINESS_NEWS_SUCCESS';
export const GET_BUSINESS_NEWS_FAIL = 'GET_BUSINESS_NEWS_FAIL';

export const GET_TECHNOLOGY_NEWS_START = 'GET_TECHNOLOGY_NEWS_START';
export const GET_TECHNOLOGY_NEWS_SUCCESS = 'GET_TECHNOLOGY_NEWS_SUCCESS';
export const GET_TECHNOLOGY_NEWS_FAIL = 'GET_TECHNOLOGY_NEWS_FAIL';

export const GET_SCIENCE_NEWS_START = 'GET_SCIENCE_NEWS_START';
export const GET_SCIENCE_NEWS_SUCCESS = 'GET_SCIENCE_NEWS_SUCCESS';
export const GET_SCIENCE_NEWS_FAIL = 'GET_SCIENCE_NEWS_FAIL';
